apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: twingate
resources:
  - ./secret.yml
  - ../../base/twingate
patches:
  - path: ./twingate-release.yml
    target:
      kind: HelmRelease
      name: twingate