apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: priceghost-frontend
  namespace: flux-system
spec:
  image: ghcr.io/abdo14m1/priceghost-frontend
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: priceghost-frontend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: priceghost-frontend
  filterTags:
    pattern: '^([0-9]{14})-[a-f0-9]+$'
    extract: '$1'
  policy:
    numerical:
      order: asc
