apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: priceghost
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@farag.tech
        name: fluxcdbot
      messageTemplate: "chore(priceghost): update images to {{range .Changed.Images}}{{.}}{{end}}"
    push:
      branch: main
  update:
    path: ./apps/base/priceghost
    strategy: Setters
