apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adguard-home
  namespace: adguard-home
spec:
  interval: 30m
  chart:
    spec:
      chart: adguard-home
      version: "5.5.*"
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: adguard-home
      interval: 12h