kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: adguard-home-config
  namespace: adguard-home
spec:
  storageClassName: local-ssd
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"