apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token
    namespace: cert-manager
type: Opaque
data:
    cloudflare-dns-token: ENC[AES256_GCM,data:8IMgUbX2dI87fGsgP6JFjDd5cvAob+8HyV26q1WkchLLz6Ox6fUYLjfNkkBKwk5cfYpEO7CjbT4=,iv:7Xn4QF4dZFEfdUPjAtWFOnaHEXcgu+dl1ZJbg7AuxQQ=,tag:qH4G4jX3H85RlX1Hb1o4yA==,type:str]
sops:
    age:
        - recipient: age1xk7pj4s5ctcl906zvdnqdpqvgankk5a990mcexwevzkcptvlvq7qzrss9s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0RE5uUm9SUjdSa2pEUW5u
            cVVqdkNLYlRkYzYvTjVYZlBGSHdaVmFUZFVJCjFxY1ZMVllRK1FFQ3VQQWQ0NXZO
            eUhmU0U2S0hkNjhFSDBNcWpGTjVEdmMKLS0tIHUwZDNZbDNJczNjdHRmRittMmJ1
            NDhiVVVZTWlKNXV1UW9acnFZbkFUU2MKO3FeeH4aq5iuMwe78Kozbk1qbD3k0IE5
            qiYWrcxbKF3oh9jnQVycvtGtZVpTSWdetRCvN9E8tBz4/mR7dGSdPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-05T05:42:51Z"
    mac: ENC[AES256_GCM,data:0RT4Y89Hy+q/17Q/UQZ1vj483DhRn4X9zAOtVHLbFxNica6MElKTVlY4kMA4XdToczu5Jwoaq7zbSibYl8CNbHTsXJE7Xugf3AiXi45ahTWQKxNmQhDrto1pbTb3CtWq9ivo71j1aZHtCzxRPOe5NzEyNwhbMTyBYRfZhpAIkG4=,iv:CkXHIo82pzuzybab8thxTvQGGc+Bmu1rTHST2LVX0Ag=,tag:F/PTT/X8eUC2Sa4IfgnEDQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
