apiVersion: v1
kind: ConfigMap
metadata:
  name: mealie-config
  namespace: mealie
data:
  DB_ENGINE: postgres
  POSTGRES_SERVER: mealie-db-rw.mealie.svc.cluster.local
  BASE_URL: https://mealie.example.com