apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: n8n
spec:
  interval: 30m
  chart:
    spec:
      chart: n8n
      version: "1.*"
      sourceRef:
        kind: HelmRepository
        name: n8n
        namespace: n8n
      interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: n8n-values
      valuesKey: values.yml