apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mealie
  namespace: mealie
  annotations:
    external-dns.alpha.kubernetes.io/hostname: mealie.farag.tech
spec:
  tls:
  - hosts:
    - mealie.farag.tech
    secretName: mealie-tls
  rules:
  - host: mealie.farag.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mealie
            port:
              number: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mealie-config
  namespace: mealie
data:
  BASE_URL: https://mealie.farag.tech