apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
resources:
  - repository.yaml
  - release.yaml
  - secret.yaml

configMapGenerator:
  - name: external-dns-values
    files:
      - values.yml=values.yml

configurations:
  - kustomizeconfig.yml
