apiVersion: v1
kind: Secret
metadata:
    name: hf-token-secret
    namespace: ai-models
type: Opaque
stringData:
    hf_token: ENC[AES256_GCM,data:jGBE9LIkeHqSIHUKfVN4cco5Mo1JoM0UTUbnYVNsX1vLkgTnpg==,iv:y9xAKTyYI9j28Us9eI/EyTv0xWR3XGZ5oDLcekXsVf0=,tag:TxgT2Chxddc2iM3rE1/z0g==,type:str]
sops:
    age:
        - recipient: age1xk7pj4s5ctcl906zvdnqdpqvgankk5a990mcexwevzkcptvlvq7qzrss9s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2SVBJcENJQTlHL0UySjhj
            a1FwdURRTWFaZ29VVXpabldPbC9VYkdYZURjCitBbWxObGx2bGlMRU9tbERiSERO
            SWRqWk8va3NaTUhlUm91QWg1dHpSWDAKLS0tIG1lN0V5N0NwVndUSUJaZ0x1V3Zs
            aUNPWGtYdExZcXk0Y3JtRFRWdHU2dVUKNALIGoCqdXyp67J3htlHm+LksPKS2Cmv
            qz+5Wakj/vJIZ51Ppsm4GzUStr1B8lL0cdDuFfpsPqB0q4rW+9PIuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-16T02:05:17Z"
    mac: ENC[AES256_GCM,data:tdi5IJKluIS1fI1J3GAmkv1Kpp2sXxp/Xs6milJZZyrrEK00sUpKOcI9dID0lTi7b/SR4jwyg6EU+hwoiiGUt/CYMP/0SiwzTtbUegffjhJiaKEEJKCpkAudbj+VfvsCKmpSlMyrFpdvJoITW46cChaeLXS7pKibFxcZCJfpxy8=,iv:QuDh4L4iiqcdYvyIZZLVqNW/KF2WnZbKQeqyXBIhb2g=,tag:nOHRdeQV0RId8EUsXQ2+qQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
