apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-config
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: infrastructure-controllers
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./infrastructure/digitalocean/config"
  prune: true
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
