apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./apps/main"
  prune: true
  timeout: 1m
  decryption:
    provider: sops
    secretRef:
      name: sops-age