apiVersion: v1
kind: Service
metadata:
  name: priceghost
  namespace: priceghost
  annotations:
    external-dns.alpha.kubernetes.io/hostname: price.farag.tech
    external-dns.alpha.kubernetes.io/target: 1f9a4c58-b90b-4572-bb91-83504ae022bd.cfargotunnel.com
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
