apiVersion: v1
kind: Secret
metadata:
  name: tunnel-credentials
  namespace: priceghost
type: Opaque
stringData:
  credentials.json: |
    {"AccountTag":"a36e90eb15090bea9d3c2ebeacee559e","TunnelSecret":"zQwruRm+tqCs08+KZOdBLzvuf8/a/5kl63k4WRoqLKs=","TunnelID":"1f9a4c58-b90b-4572-bb91-83504ae022bd","Endpoint":""}
