apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflare-tunnel
  namespace: cloudflare
spec:
  interval: 1h
  chart:
    spec:
      chart: cloudflare-tunnel-remote
      version: "0.*"
      sourceRef:
        kind: HelmRepository
        name: cloudflare
        namespace: cloudflare

  valuesFrom:
    - kind: Secret
      name: cloudflare-tunnel-values
      valuesKey: values.yml
