apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/cloudflare-tunnel
patches:
- patch: |-
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      name: cloudflare-tunnel
      namespace: cloudflare
    spec:
      valuesFrom:
      - kind: Secret
        name: cloudflare-tunnel-values
        valuesKey: values.yml
  target:
    kind: HelmRelease
    name: cloudflare-tunnel
    namespace: cloudflare