apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-values
    namespace: cloudflare
data:
    values.yml: ENC[AES256_GCM,data:sGaeivZNDWvEn342Hfz/P3QO9Kdn1A0l7wsqGehFFNdaUU/ZpVPLqkrW3A3T10x0Ftw66urZ605ZGKTBsPp2kbVVN+VIKbgXT1jahi7yZHq5rPMrCVRRJVW3V5KVjdkH99CaOV7RwpUpEREn6TD5+MfIfE/Rb2yenB8GHPEhGYOGT6g1CXSGwvoQtNaDktxII3YAykH3lxNe6w1847p8l9dB+74wGCu1p6rYXDGQFnp+eG1j8iabQqR5DktZNq/ij0OQlEWZznzf3tsXjJ9wIhq1VuqapnalCW8ETQsN5hj/qonWFbySuTLLYbqn9u/YodUw0LtIbSA9ge71DPXPD4UI+gUUoErpe8w4aZOqzlahGxEd0CELBu+eebvOH5CVhM31nr8j/u1atYe9mYa8Hj2OUUFowFiJ,iv:UW+liIVkuhAaRKARJKQ4akIPXnDNiRE6otio8VBhJxY=,tag:uWeo0cdc+/W357niWcvThg==,type:str]
sops:
    age:
        - recipient: age1xk7pj4s5ctcl906zvdnqdpqvgankk5a990mcexwevzkcptvlvq7qzrss9s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRGlvYklkalYwRG12RC9G
            QlhyaWk0eWswK2twcEt2a242M1pwb1BFZEhnCkFOSEw0UzVqS0gwakFZUnRLN3NN
            NXpENHA1Sjk0SmNUMGpmdjRIa1lRN0kKLS0tIDQ2ZHJIbi9JeUZJU2d4eUk5UTAz
            Z3lkd3RBT29JYThrWTlWUWNXZlE5cUUKyYifHSX+AWQdvmCKM7PIOuYf/K66VpiP
            fyfaSZhZQ3MrYjOKut9DLVR/ypeOjVd4I4hzB9hIacdroIltq7vjlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-04T04:21:13Z"
    mac: ENC[AES256_GCM,data:IiQaWKilPlYDWIhYgrsUDic9zztqSpAQ/ksxJ44CQDTIo9CAcD+b5okdKNMDlNAvbUh+Nn197oKR+u80HMo8HlCfZXbuuKfy5Av1qAqZyXP1p6EzTRJKZZDVAZyO/au6es8M30Qx7OzI7xnmh6js9zcrY0jHmUEtuz4avkfay9Y=,iv:da0fEyEskQql+WgeHAkZzSsLvrDkeQBVcxToNoGH3dw=,tag:4jmx7SODeKCMa2zqCjaYRQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
