apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kroki
  namespace: kroki
spec:
  interval: 30m
  chart:
    spec:
      chart: kroki
      version: "1.*"
      sourceRef:
        kind: HelmRepository
        name: cowboysysop
        namespace: kroki 
      interval: 12h
  valuesFrom:
  - kind: ConfigMap
    name: kroki-values
    valuesKey: values.yml