apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: priceghost-backend
  name: priceghost-backend
  namespace: priceghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: priceghost-backend
  template:
    metadata:
      labels:
        app: priceghost-backend
    spec:
      containers:
        - image: ghcr.io/abdo14m1/priceghost-backend:20260323212650-29c7374 # {"$imagepolicy": "flux-system:priceghost-backend"}
          name: priceghost-backend
          envFrom:
            - configMapRef:
                name: priceghost-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: priceghost-secrets
                  key: database-url
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: priceghost-secrets
                  key: jwt-secret
          ports:
            - containerPort: 3001
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
