apiVersion: v1
kind: Secret
metadata:
    name: priceghost-database-user
    namespace: priceghost
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:J2I64cH5hdhq3A==,iv:JZaFpGy7VEM5PBxJwyB2NMb+nrVkZB4yo/z3JSmmikU=,tag:PfKtLicP/du3Uibdbjn+JQ==,type:str]
    password: ENC[AES256_GCM,data:A6JvAkYqEQg=,iv:TwWjuv+bALTF7WKS0vcUyy5vT7NOtcTuKh8HLWQOmK8=,tag:lh+HLnoBhMvuoRBV91X3Yg==,type:str]
sops:
    age:
        - recipient: age1xk7pj4s5ctcl906zvdnqdpqvgankk5a990mcexwevzkcptvlvq7qzrss9s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2OExzWjFka3Nkd01RMkdW
            VE95bndEYXYxa2ZKMjhleVNzcVdQYnVCYlQ4ClVhRGhvU3lQSDdaR1lNS1NEeDg2
            bFM5SnNhRE5IRGV3RGxMbU5XQjkvR0UKLS0tIGxZZ1BsSThzQnJwVGxBa2dpRE80
            bC91Ym1XZGhISFJFTXJzOUFzUjRnRjgK4OG9KCOSbjk3lAQLzOVl2D1E2EpM7B5q
            hxH9AW7Y8W9bFbgqFRVAlqT8UY5+2XUiK90+BE7DD1POX8oScuBENA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T11:34:43Z"
    mac: ENC[AES256_GCM,data:7chZ2t0ImLgBJw2YD2ky0FdBPcbWB+3Psucu2MpAk7WS4wgq784UAd3HwSmbBMYXkH07n08DP5fIcoSdlnjMntHvlrHMLSZPwgmqyXCcoFmig5Uh9E9q1OKpSLIhNKNmGTxMFoVtMbmpw79ggMN/6Z2GFWrEZWi93r/i/FjOZPg=,iv:3Qet11MfaJth8nwMDxXEsF0dqGB/elbuwG93NdDEzUI=,tag:IBt9C6BJr134j8m+6MhSbA==,type:str]
    encrypted_regex: ^(data|stringData)
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: priceghost-secrets
    namespace: priceghost
type: Opaque
stringData:
    database-url: ENC[AES256_GCM,data:zDnbx5W+ETLhaJHtNKowMOwmp/A9m4wt2b+Ul2hIeQQJjAlLXjmfbfSzktCAOG7jTBzm3v8Kuk4V0e0LtBIBtuo=,iv:zXJ0RVjlmK6GOJWybpPLYefsUTJaPD9unLneTxVbjK0=,tag:6YGE+DLahU5BUlGlEIF2pQ==,type:str]
    jwt-secret: ENC[AES256_GCM,data:ZCwKCceJypY=,iv:nbVIYSyRy2zUaNeQDZNMTDlUPU4qJme3ZzRbywGOgwg=,tag:eb6Ilg+HnkRCvKANaUbDBA==,type:str]
sops:
    age:
        - recipient: age1xk7pj4s5ctcl906zvdnqdpqvgankk5a990mcexwevzkcptvlvq7qzrss9s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2OExzWjFka3Nkd01RMkdW
            VE95bndEYXYxa2ZKMjhleVNzcVdQYnVCYlQ4ClVhRGhvU3lQSDdaR1lNS1NEeDg2
            bFM5SnNhRE5IRGV3RGxMbU5XQjkvR0UKLS0tIGxZZ1BsSThzQnJwVGxBa2dpRE80
            bC91Ym1XZGhISFJFTXJzOUFzUjRnRjgK4OG9KCOSbjk3lAQLzOVl2D1E2EpM7B5q
            hxH9AW7Y8W9bFbgqFRVAlqT8UY5+2XUiK90+BE7DD1POX8oScuBENA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T11:34:43Z"
    mac: ENC[AES256_GCM,data:7chZ2t0ImLgBJw2YD2ky0FdBPcbWB+3Psucu2MpAk7WS4wgq784UAd3HwSmbBMYXkH07n08DP5fIcoSdlnjMntHvlrHMLSZPwgmqyXCcoFmig5Uh9E9q1OKpSLIhNKNmGTxMFoVtMbmpw79ggMN/6Z2GFWrEZWi93r/i/FjOZPg=,iv:3Qet11MfaJth8nwMDxXEsF0dqGB/elbuwG93NdDEzUI=,tag:IBt9C6BJr134j8m+6MhSbA==,type:str]
    encrypted_regex: ^(data|stringData)
    version: 3.11.0
