apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: n8n-db
  namespace: n8n
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:14.19-minimal-bookworm
  instances: 1
  bootstrap:
    initdb:
      database: n8n
      owner: n8n
      secret:
        name: n8n-database-creds
  storage:
    size: 2Gi
    storageClass: local-ssd
  managed:
    services:
      disabledDefaultServices:
      - ro
      - r
