apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: twingate
resources:
  - ./secret.yaml
  - ../../base/twingate
patches:
  - path: ./twingate-release.yaml
    target:
      kind: HelmRelease
      name: twingate