apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/cilium
configMapGenerator:
  - name: cilium-config
    files:
      - values.yml=values.yml
configurations:
  - kustomizeconfig.yml 