apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/vllm-whisper-turbo
  - namespace.yaml
  - secret.yaml
  - httproute.yaml
namespace: ai-models
patches:
  - path: isvc-patch.yaml
    target:
      name: whisper-turbo
      kind: InferenceService