apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: whisper-turbo
  namespace: ai-models
spec:
  predictor:
    runtimeClassName: nvidia
    minReplicas: 1    
    maxReplicas: 1
    model:
      modelFormat:
        name: huggingface
      args:
        - --model_id=openai/whisper-large-v3-turbo
        - --backend=vllm
        - --dtype=float16
        - --gpu-memory-utilization=0.9 # Recommended for vLLM to avoid OOM
      env:
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-token-secret
              key: hf_token
      resources:
        requests:
          cpu: "2"
          memory: "8Gi"   # Bumped up slightly for safety
          nvidia.com/gpu: "1"
        limits:
          cpu: "4"
          memory: "16Gi"  # Whisper Large needs significant RAM for weight loading
          nvidia.com/gpu: "1"