apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisper-model-pvc
  namespace: ai-models
spec:
  storageClassName: local-ssd
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi