apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: whisper-vllm-runtime
spec:
  supportedModelFormats:
    - name: vllm
      autoSelect: true
  containers:
    - name: kserve-container
      image: vllm/vllm-openai:nightly
      ports:
        - containerPort: 8080
          protocol: TCP
      env:
        - name: PORT
          value: "8080"
        - name: HUGGING_FACE_HUB_CACHE
          value: "/mnt/models"
      args:
        - "--model"
        - "openai/whisper-large-v3-turbo"
        - "--task"
        - "transcription"
        - "--trust-remote-code"
      resources:
        limits:
          cpu: "4"
          memory: "16Gi"
          nvidia.com/gpu: "1"
        requests:
          cpu: "2"
          memory: "8Gi"
          nvidia.com/gpu: "1"
      volumeMounts:
        - name: model-cache
          mountPath: /mnt/models
  volumes:
    - name: model-cache
      persistentVolumeClaim:
        claimName: whisper-model-pvc