apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-connector
  namespace: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
        - "tunnel"
        - "--config"
        - "/etc/cloudflared/config/config.yaml"
        - "run"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/cloudflared/config
          readOnly: true
        - name: creds-volume
          mountPath: /etc/cloudflared/creds
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: cloudflared-config
      - name: creds-volume
        secret:
          secretName: tunnel-credentials