apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
    name: n8n-db
    namespace: n8n
spec:
    imageName: ghcr.io/cloudnative-pg/postgresql:14.19-minimal-bookworm
    instances: 1
    bootstrap:
        initdb:
            database: n8n
            owner: n8n
            secret:
                name: n8n-database-creds
    storage:
        size: 2Gi
        storageClass: local-ssd
    managed:
        services:
            disabledDefaultServices:
                - ro
                - r
sops:
    age:
        - recipient: age1xk7pj4s5ctcl906zvdnqdpqvgankk5a990mcexwevzkcptvlvq7qzrss9s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1UzUrV2xxVWU1UXhoaVVH
            QThFWXdCdDVXVUpqQjN3Q0xhN2VEc3NVblNNCmJON0NicmtlbGdFNlIzQXNNY2dG
            VHFzRnQ5eEtKWlFOWXE3eTNwUGt1Zk0KLS0tIG0xZ1RqSlVOLzZ5R2hXSHhRSXJH
            VDZ6M0k5NUkySE5QYmpBaWNQSUdwVUEKTfF02zktOeiMU+Un8Ypn79t5icvIg268
            UkWG+41P8Uw6OBUBjRQ7MqcD0eYXkI5p6YQsewfgAo1miun/gE2GVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-12T02:51:06Z"
    mac: ENC[AES256_GCM,data:b+w3d3Y3IsQFwnUGPseSgzevOZru9603pYVoc06JhgluDK7n75BFK8FVoFSpEu1UE2uASUiOTphC4zxsSRTnwfFuZJVijITIcpA/eBuH6wlboSqHp+9FdOkdaiHz5Xzilo52rUS8OjOvhu2rlHYAtr5JMSdGju3dsrVUeQxN4bc=,iv:xA1dGsCav2BdOA9XV8ezXcAlEpIYZEtkYmIw+VBPyOQ=,tag:Zt0c23bjA1DiiE1UEIN1oA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: n8n-database-creds
    namespace: n8n
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:J350,iv:felIpsRjGXpxNM0bDrHYC2Ajxiaepf8Vsw5T/QKQrcM=,tag:XL3jqxCq/38mJx7C+5ITEQ==,type:str]
    password: ENC[AES256_GCM,data:otbu9bfCZWuAFwkZsvCv5Q==,iv:LBP3KEa/mOk2/0pIOYxYHQK9lVDlar8I91+OmZgqv8Y=,tag:F98oaBc913E7m1HOiNmqow==,type:str]
sops:
    age:
        - recipient: age1xk7pj4s5ctcl906zvdnqdpqvgankk5a990mcexwevzkcptvlvq7qzrss9s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1UzUrV2xxVWU1UXhoaVVH
            QThFWXdCdDVXVUpqQjN3Q0xhN2VEc3NVblNNCmJON0NicmtlbGdFNlIzQXNNY2dG
            VHFzRnQ5eEtKWlFOWXE3eTNwUGt1Zk0KLS0tIG0xZ1RqSlVOLzZ5R2hXSHhRSXJH
            VDZ6M0k5NUkySE5QYmpBaWNQSUdwVUEKTfF02zktOeiMU+Un8Ypn79t5icvIg268
            UkWG+41P8Uw6OBUBjRQ7MqcD0eYXkI5p6YQsewfgAo1miun/gE2GVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-12T02:51:06Z"
    mac: ENC[AES256_GCM,data:b+w3d3Y3IsQFwnUGPseSgzevOZru9603pYVoc06JhgluDK7n75BFK8FVoFSpEu1UE2uASUiOTphC4zxsSRTnwfFuZJVijITIcpA/eBuH6wlboSqHp+9FdOkdaiHz5Xzilo52rUS8OjOvhu2rlHYAtr5JMSdGju3dsrVUeQxN4bc=,iv:xA1dGsCav2BdOA9XV8ezXcAlEpIYZEtkYmIw+VBPyOQ=,tag:Zt0c23bjA1DiiE1UEIN1oA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
