apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: n8n
  namespace: n8n
resources:
- namespace.yml
- ../../base/n8n
configMapGenerator:
  - name: n8n-values
    files:
      - values.yml=values.yml
configurations:
  - kustomizeconfig.yml