namespaceOverride: kroki
ingress:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: kroki.farag.tech
    cert-manager.io/cluster-issuer: letsencrypt-prod
  pathType: Prefix
  ingressClassName: cilium
  enabled: true
  hosts:
  - host: kroki.farag.tech
    paths:
    - /
  tls:
  - hosts:
    - kroki.farag.tech
    secretName: kroki-tls